---
name: ⬆️ Release to Edge

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      artifact-id:
        description: "(Optional) The name of the artifact to use for the release"
        required: false
        type: string
        default: ${{ github.sha }}

permissions:
  id-token: write # This is required for requesting the JWT google-github-actions/auth
  contents: read # This is required for checking out the repository

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy-app-engine.yml
    with:
      artifact-id: ${{ github.sha }}
      gcp-project-id: ${{ vars.GCLOUD_PROJECT_ID }}
      gcp-version: edge
      gcp-service-account: ${{ vars.GCLOUD_SERVICE_ACCOUNT }}
    secrets:
      gcp-service-account-key-json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_JSON }}
