---
name: Build and Push Node To App Engine
on:
  push:
    branches: [main]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for checking out the repository

jobs:
  build-and-push:
    name: Build and Push to GCP App Engine
    runs-on: ubuntu-latest
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_JSON }}
          service_account: "halocare-test@appspot.gserviceaccount.com"

      - name: Print Current Path
        run: pwd

      - name: List Files in Directory
        run: ls

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v2"
        with:
          deliverables: app.yaml
