---
name: Build and Push Node To App Engine
on:
  push:
    branches: [main]

permissions:
  id-token: write # This is required for requesting the JWT google-github-actions/auth@v2
  contents: read # This is required for checking out the repository

jobs:
  build-and-push:
    name: Build and Push to GCP App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: npm install
        run: |
          npm install

      - name: eslint
        run: npm run lint
      
      - name: prettier check
        run: npm run format:check

      - name: build
        run: npm run build --if-present

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_JSON }}
          service_account: ${{ vars.GCLOUD_SERVICE_ACCOUNT }}

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v2"
        with:
          deliverables: app.yaml
          project_id: ${{ vars.GCLOUD_PROJECT_ID }}
